version: '3.8'
services:
  componentb:
    build:
      context: ./componentB
    container_name: componentb
    ports:
      - "8000:8000"
    volumes:
      - ./componentB/database:/app/database

  componenta:
    build:
      context: ./componentA
    container_name: componenta
    ports:
      - "5000:5000"
    depends_on:
      - componentb
